[project]
name = "statistical-modeling-of-time-series-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "requests>=2.32.5",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
]
